[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch @ https://r2.drysys.workers.dev/torch/11.8/torch-2.1.0-cp311-cp311-linux_x86_64.whl",
    "wheel",
]
build-backend = "setuptools.build_meta"
